import { Employee, Shift, EmployeeShiftMapping, ShiftDef } from './calendar.model';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'EMP-001',
    employeeId: 'EMP-001',
    name: 'Rahul Mehta',
    email: 'rahul.mehta@company.com',
    contactNo: '+91 9876543210',
    joiningDate: '2024-01-15',
    image: 'base64_img_string_or_url',
    address: 'Mumbai, Maharashtra',
    idNumber: 'ID-9928',
    dept: 'Operations',
    role: 'Senior Operator',
    gender: 'Male',
    shift: 'Morning',
    status: 'Active',
    expiry: '2026-12-31',
    backup: false,
    consent: true,
  },
  {
    id: 'EMP-002',
    employeeId: 'EMP-002',
    name: 'Priya Sharma',
    email: 'priya.sharma@company.com',
    contactNo: '+91 9876543211',
    joiningDate: '2024-02-10',
    image: 'base64_img_string_or_url',
    address: 'Delhi, NCR',
    idNumber: 'ID-9929',
    dept: 'Operations',
    role: 'Operator',
    gender: 'Female',
    shift: 'Afternoon',
    status: 'Active',
    expiry: '2026-06-30',
    backup: false,
    consent: true,
  },
  {
    id: 'EMP-003',
    employeeId: 'EMP-003',
    name: 'Ananya Krishna',
    email: 'ananya.k@company.com',
    contactNo: '+91 9876543212',
    joiningDate: '2024-03-22',
    image: 'base64_img_string_or_url',
    address: 'Chennai, Tamil Nadu',
    idNumber: 'ID-9930',
    dept: 'Operations',
    role: 'Junior Operator',
    gender: 'Female',
    shift: 'Night',
    status: 'Active',
    expiry: '2025-08-15',
    backup: false,
    consent: false,
  },
  {
    id: 'EMP-004',
    employeeId: 'EMP-004',
    name: 'Suresh Tiwari',
    email: 'suresh.tiwari@company.com',
    contactNo: '+91 9876543213',
    joiningDate: '2024-04-05',
    image: 'base64_img_string_or_url',
    address: 'Bangalore, Karnataka',
    idNumber: 'ID-9931',
    dept: 'IT',
    role: 'Tech Lead',
    gender: 'Male',
    shift: 'Morning',
    status: 'Active',
    expiry: '2027-03-31',
    backup: true,
    consent: true,
  },
  {
    id: 'EMP-005',
    employeeId: 'EMP-005',
    name: 'Meena Kapoor',
    email: 'meena.k@company.com',
    contactNo: '+91 9876543214',
    joiningDate: '2024-05-18',
    image: 'base64_img_string_or_url',
    address: 'Hyderabad, Telangana',
    idNumber: 'ID-9932',
    dept: 'IT',
    role: 'Developer',
    gender: 'Female',
    shift: 'Afternoon',
    status: 'Active',
    expiry: '2026-09-30',
    backup: false,
    consent: true,
  },
  {
    id: 'EMP-006',
    employeeId: 'EMP-006',
    name: 'Arjun Tomar',
    email: 'arjun.tomar@company.com',
    contactNo: '+91 9876543215',
    joiningDate: '2024-06-01',
    image: 'base64_img_string_or_url',
    address: 'Pune, Maharashtra',
    idNumber: 'ID-9933',
    dept: 'Security',
    role: 'Security Lead',
    gender: 'Male',
    shift: 'Night',
    status: 'Active',
    expiry: '2025-12-31',
    backup: false,
    consent: true,
  },
  {
    id: 'EMP-007',
    employeeId: 'EMP-007',
    name: 'Kiran Bhat',
    email: 'kiran.bhat@company.com',
    contactNo: '+91 9876543216',
    joiningDate: '2024-07-15',
    image: 'base64_img_string_or_url',
    address: 'Kochi, Kerala',
    idNumber: 'ID-9934',
    dept: 'Security',
    role: 'Guard',
    gender: 'Male',
    shift: 'Any',
    status: 'Active',
    expiry: '2026-06-15',
    backup: true,
    consent: true,
  },
  {
    id: 'EMP-008',
    employeeId: 'EMP-008',
    name: 'Lakshmi Iyer',
    email: 'lakshmi.iyer@company.com',
    contactNo: '+91 9876543217',
    joiningDate: '2024-08-20',
    image: 'base64_img_string_or_url',
    address: 'Chennai, Tamil Nadu',
    idNumber: 'ID-9935',
    dept: 'Admin',
    role: 'Admin Exec',
    gender: 'Female',
    shift: 'Morning',
    status: 'On Leave',
    expiry: '2027-01-31',
    backup: false,
    consent: true,
  },
];

export const DEFAULT_SHIFT_DEFS: { [key: string]: ShiftDef } = {
  General: {
    label: 'General Shift',
    time: '09:00 – 18:00',
    cls: 'shift-general',
    bg: '#4CAF50',
    color: '#fff',
  },
  A: { label: 'A Shift', time: '06:00 – 14:00', cls: 'shift-a', bg: '#2196F3', color: '#fff' },
  B: { label: 'B Shift', time: '14:00 – 22:00', cls: 'shift-b', bg: '#9C27B0', color: '#fff' },
  Night: {
    label: 'Night Shift',
    time: '22:00 – 06:00',
    cls: 'shift-night',
    bg: '#3C3489',
    color: '#fff',
  },
  Leave: { label: 'Leave', time: '', cls: 'shift-leave', bg: '#FAEEDA', color: '#854F0B' },
  Holiday: { label: 'Holiday', time: '', cls: 'shift-holiday', bg: '#FCEBEB', color: '#A32D2D' },
  Backup: { label: 'Backup', time: '', cls: 'shift-backup', bg: '#E1F5EE', color: '#0F6E56' },
};

export const DEFAULT_SHIFTS: Shift[] = [
  {
    name: 'General Shift',
    startTime: '09:00:00',
    endTime: '18:00:00',
    weekDays: 'Monday,Tuesday,Wednesday,Thursday,Friday',
    isOperational: true,
    doesShiftFallOnNextDay: false,
    shiftInterval: '9 Hours',
  },
  {
    name: 'A Shift',
    startTime: '06:00:00',
    endTime: '14:00:00',
    weekDays: 'Monday,Tuesday,Wednesday,Thursday,Friday',
    isOperational: true,
    doesShiftFallOnNextDay: false,
    shiftInterval: '8 Hours',
  },
  {
    name: 'B Shift',
    startTime: '14:00:00',
    endTime: '22:00:00',
    weekDays: 'Monday,Tuesday,Wednesday,Thursday,Friday',
    isOperational: true,
    doesShiftFallOnNextDay: false,
    shiftInterval: '8 Hours',
  },
  {
    name: 'Night Shift',
    startTime: '22:00:00',
    endTime: '06:00:00',
    weekDays: 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday',
    isOperational: true,
    doesShiftFallOnNextDay: true,
    shiftInterval: '8 Hours',
  },
];

export const INITIAL_SHIFT_MAPPINGS: EmployeeShiftMapping[] = [
  {
    employeeId: 'EMP-001',
    startDate: '2026-05-26',
    endDate: '2026-05-31',
    shiftId: 'General Shift',
  },
  {
    employeeId: 'EMP-001',
    startDate: '2026-05-26',
    endDate: '2026-05-26',
    shiftId: 'A Shift',
  },
  {
    employeeId: 'EMP-002',
    startDate: '2026-05-26',
    endDate: '2026-05-30',
    shiftId: 'General Shift',
  },
  {
    employeeId: 'EMP-003',
    startDate: '2026-06-20',
    endDate: '2026-06-25',
    shiftId: 'Night Shift',
  }
];
